version: '3.4'

services:
  carcatalog.postgres:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5431:5431"
    command: 
      - "postgres"
      - "-c"
      - "port=5431"
    networks:
      - shared.carcatalog.net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  carcatalog.api:
    ports:
      - "10000:8080"
    networks:
      - shared.carcatalog.net
    env_file:
      - env.api

networks:
  shared.carcatalog.net:
    name: car_catalog_net
    driver: bridge
