version: '3.4'

services:
  carcatalog.postgres:
    image: postgres:latest

  carcatalog.api:
    image: ${DOCKER_REGISTRY-}carcatalogapi
    build:
      context: .
      dockerfile: CarCatalog.Api/Dockerfile
    depends_on:
      - carcatalog.postgres
