using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace CarCatalog.Entities.Common;

/// <summary>
///     Represents the base entity for the application data model.
/// </summary>
public abstract class BaseEntity
{
    /// <summary>
    ///     Gets or sets the unique identifier for the entity.
    /// </summary>
    /// <remarks>
    ///     The property serves as the primary key for entities that inherit from <see cref="BaseEntity"/>.
    ///     The property is decorated with the <seealso cref="KeyAttribute"/>, indicating it is the primary key,
    ///     and the <seealso cref="DatabaseGeneratedAttribute"/> is used to specify that the value is generated by the database.
    /// </remarks>
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }
}
